// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeographicPosition } from "./GeographicPosition";

export interface AircraftSummary { icao: number, callsign: string, altitude: number, geoPosition: GeographicPosition | null, lastContact: bigint, }